name: Build Mod
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: "11"
        distribution: "temurin"
    - uses: android-actions/setup-android@v2
    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c
    - name: Build Native Lib
      run: |
        cd mod_menu_rootless/jni
        $ANDROID_NDK_HOME/ndk-build NDK_PROJECT_PATT=. APP_BUILD_SCRIPT=Android.mk
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: liv
        path: mod_menu_rootless/libs/